from pathlib import Path
import re

root = Path('source')

# 1) Generate exact route CSS/body-page metadata from the main HTML sources at every build.
p = root / 'frontend-react/scripts/copy-legacy-assets.mjs'
s = p.read_text(encoding='utf-8')
s = s.replace('import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";', 'import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";')
marker = '\n\nconst parityCssFiles = ['
if marker not in s:
    raise SystemExit('copy-legacy-assets parity CSS marker missing')
s = s.split(marker, 1)[0].rstrip() + '\n'
route_gen = r'''

const routeSources = {
  "/": "index.html",
  "/catalogo": "catalogo.html",
  "/mappa": "mappa.html",
  "/blog": "blog.html",
  "/blog/:detail": "blog-articolo.html",
  "/attivita/:detail": "attivita.html",
  "/login": "login.html",
  "/registrazione": "registrazione.html",
  "/profilo": "profilo.html",
  "/preferiti": "preferiti.html",
  "/dashboard": "dashboard.html",
  "/messaggi": "messaggi.html",
  "/aggiungi-attivita": "aggiungi-attivita.html",
  "/chi-siamo": "chi-siamo.html",
  "/contatti": "contatti.html",
  "/privacy-policy": "privacy-policy.html",
  "/cookie-policy": "cookie-policy.html",
  "/termini": "termini.html",
  "/note-legali": "note-legali.html",
  "/backup": "backup.html",
  "/admin": "pages/admin/index.html",
  "/admin/attivita": "pages/admin/attivita.html",
  "/admin/recensioni": "pages/admin/recensioni.html",
  "/admin/segnalazioni": "pages/admin/segnalazioni.html",
  "/admin/blog": "pages/admin/blog.html",
  "/admin/categorie": "pages/admin/categorie.html",
  "/admin/comuni": "pages/admin/comuni.html",
  "/admin/utenti": "pages/admin/utenti.html",
  "/admin/messaggi": "pages/admin/messaggi.html",
  "/admin/comunicazioni": "pages/admin/comunicazioni.html",
  "/admin/seo": "pages/admin/seo.html",
  "/admin/sistema": "pages/admin/sistema.html",
  "/admin/impostazioni": "pages/admin/impostazioni.html",
  "/admin/backup": "pages/admin/backup.html",
};
const routeCss = {};
const routePages = {};
const cssFiles = new Set();
for (const [route, relative] of Object.entries(routeSources)) {
  const source = resolve(repoRoot, relative);
  if (!existsSync(source)) continue;
  const raw = readFileSync(source, "utf8");
  const styles = [...raw.matchAll(/<link\b[^>]*rel=["']stylesheet["'][^>]*href=["']([^"']+)["'][^>]*>/gi)]
    .map((match) => match[1])
    .filter((href) => href.startsWith("/assets/css/"));
  routeCss[route] = styles;
  for (const href of styles) cssFiles.add(href.slice(1));
  const page = raw.match(/<body\b[^>]*\bdata-page=["']([^"']+)["']/i)?.[1] || "";
  if (page) routePages[route] = page;
}
for (const relative of cssFiles) {
  const source = resolve(repoRoot, relative);
  if (!existsSync(source)) throw new Error(`CSS main non trovato: ${source}`);
  const target = resolve(reactRoot, "public", relative);
  mkdirSync(dirname(target), { recursive: true });
  copyFileSync(source, target);
}
const routeModule = `export const MAIN_ROUTE_CSS: Record<string, readonly string[]> = ${JSON.stringify(routeCss, null, 2)};\nexport const MAIN_ROUTE_PAGE: Record<string, string> = ${JSON.stringify(routePages, null, 2)};\n`;
writeFileSync(resolve(generatedDir, "main-route-css.ts"), routeModule, "utf8");
console.log(`Parità route generata: ${Object.keys(routeCss).length} route, ${cssFiles.size} CSS main`);
'''
s += route_gen

# Contacts has an empty <main> in main; reproduce the exact content generated by page-loader-core.js.
needle = '  let html = mainMatch?.[1] || "";\n'
replacement = r'''  let html = mainMatch?.[1] || "";
  if (kind === "contacts" && !html.trim()) {
    const loader = readFileSync(resolve(repoRoot, "assets/js/page-loader-core.js"), "utf8");
    const dynamic = loader.match(/contacts:\s*\["Contatti",\s*`([\s\S]*?)`\]/);
    if (!dynamic) throw new Error("Contenuto Contatti dinamico non trovato nel main");
    html = `<section class="section container"><p class="eyebrow">CalabriaVera</p><h1>Contatti</h1><div class="prose">${dynamic[1]}</div></section>`;
  }
'''
if needle not in s:
    raise SystemExit('legal generator marker missing')
s = s.replace(needle, replacement, 1)
p.write_text(s, encoding='utf-8')

# Remove obsolete concatenated CSS artifact if present.
obsolete = root / 'frontend-react/src/generated/main-parity.css'
if obsolete.exists(): obsolete.unlink()

# 2) Layout uses generated source-of-truth route metadata and preserves server-injected links on first paint.
p = root / 'frontend-react/src/components/Layout.tsx'
s = p.read_text(encoding='utf-8')
if 'MAIN_ROUTE_CSS' not in s.split('\n', 12)[0:12]:
    s = s.replace('import PwaInstallButton from "./PwaInstallButton";\n', 'import PwaInstallButton from "./PwaInstallButton";\nimport { MAIN_ROUTE_CSS, MAIN_ROUTE_PAGE } from "../generated/main-route-css";\n')
start = s.find('const MAIN_COMMON_CSS = [')
end = s.find('\n\nfunction AccountIcon()', start)
if start < 0 or end < 0:
    raise SystemExit('Layout CSS helper block missing')
helper = r'''function mainRouteKey(path: string) {
  if (MAIN_ROUTE_CSS[path]) return path;
  if (path.startsWith("/blog/")) return "/blog/:detail";
  if (path === "/attivita" || path.startsWith("/attivita/")) return "/attivita/:detail";
  return path;
}

function exactMainCss(path: string) {
  return [...(MAIN_ROUTE_CSS[mainRouteKey(path)] || [])];
}

function exactMainPage(path: string) {
  return MAIN_ROUTE_PAGE[mainRouteKey(path)] || "";
}'''
s = s[:start] + helper + s[end:]

old_page = r'''    const page = cleanPath === "/" ? "home"
      : cleanPath === "/catalogo" ? "catalog"
      : cleanPath === "/mappa" ? "map"
      : cleanPath === "/blog" || cleanPath.startsWith("/blog/") ? "blog"
      : cleanPath === "/chi-siamo" ? "about"
      : cleanPath === "/contatti" ? "contacts"
      : cleanPath === "/privacy-policy" ? "privacy"
      : cleanPath === "/cookie-policy" ? "cookies"
      : cleanPath === "/termini" ? "terms"
      : cleanPath === "/note-legali" ? "legal"
      : cleanPath === "/attivita" || cleanPath.startsWith("/attivita/") ? "activities"
      : cleanPath === "/login" ? "login"
      : cleanPath === "/registrazione" ? "register"
      : cleanPath.replace(/^\//, "") || "app";'''
new_page = r'''    const page = exactMainPage(cleanPath) || (cleanPath.startsWith("/admin/") ? `admin-${cleanPath.split("/").filter(Boolean).at(-1)}` : cleanPath.replace(/^\//, "") || "app");'''
if old_page not in s:
    raise SystemExit('Layout body page mapping block missing')
s = s.replace(old_page, new_page, 1)

old_effect = r'''  useEffect(() => {
    const expected = exactMainCss(cleanPath);
    document.querySelectorAll<HTMLLinkElement>('link[data-cv-main-parity]').forEach((node) => node.remove());
    for (const href of expected) {
      const link = document.createElement("link");
      link.rel = "stylesheet";
      link.href = href;
      link.dataset.cvMainParity = "";
      document.head.appendChild(link);
    }
    return () => document.querySelectorAll<HTMLLinkElement>('link[data-cv-main-parity]').forEach((node) => node.remove());
  }, [snapshot, cleanPath]);'''
new_effect = r'''  useEffect(() => {
    const expected = exactMainCss(cleanPath);
    const nodes = [...document.querySelectorAll<HTMLLinkElement>('link[data-cv-main-parity]')];
    const current = nodes.map((node) => new URL(node.href, location.origin).pathname);
    if (current.length === expected.length && current.every((href, index) => href === expected[index])) return;
    nodes.forEach((node) => node.remove());
    for (const href of expected) {
      const link = document.createElement("link");
      link.rel = "stylesheet";
      link.href = href;
      link.dataset.cvMainParity = "";
      document.head.appendChild(link);
    }
  }, [snapshot, cleanPath]);'''
if old_effect not in s:
    raise SystemExit('Layout route CSS effect missing')
s = s.replace(old_effect, new_effect, 1)

# Show anonymous header actions immediately while auth resolves, matching main first paint.
s = s.replace('{!authReady ? <AuthPlaceholder /> : user ? <details', '{!authReady ? <div className="cv-guest-actions guest-actions"><Link href={withLanguage("/login", language)} className="cv-login-button">{uiText("login", language)}</Link><Link href={withLanguage("/registrazione", language)} className="cv-register-button">{uiText("register", language)}</Link></div> : user ? <details', 1)
p.write_text(s, encoding='utf-8')

# 3) Worker injects exact source CSS before React boots, eliminating first-paint layout drift.
p = root / 'frontend-react/worker.ts'
s = p.read_text(encoding='utf-8')
if not s.startswith('import { MAIN_ROUTE_CSS'):
    s = 'import { MAIN_ROUTE_CSS } from "./src/generated/main-route-css";\n\n' + s
helper_marker = 'function normalizeRoutePath(pathname: string) {'
helper_pos = s.find(helper_marker)
if helper_pos < 0:
    raise SystemExit('worker route helper marker missing')
css_helper = r'''function mainRouteKey(path: string) {
  if (MAIN_ROUTE_CSS[path]) return path;
  if (path.startsWith("/blog/")) return "/blog/:detail";
  if (path === "/attivita" || path.startsWith("/attivita/")) return "/attivita/:detail";
  return path;
}

function mainParityLinks(path: string) {
  const styles = MAIN_ROUTE_CSS[mainRouteKey(path)] || [];
  return styles.map((href) => `<link rel="stylesheet" href="${href}" data-cv-main-parity>`).join("");
}

'''
if 'function mainParityLinks(' not in s:
    s = s[:helper_pos] + css_helper + s[helper_pos:]

needle = '  rawHtml = localizeFirstPaint(rawHtml, url);\n  const rewritten = rewriteRobots(rawHtml, url);'
replacement = '  rawHtml = localizeFirstPaint(rawHtml, url);\n  const parityLinks = mainParityLinks(path);\n  if (parityLinks) rawHtml = rawHtml.replace("</head>", `${parityLinks}</head>`);\n  const rewritten = rewriteRobots(rawHtml, url);'
if needle not in s:
    raise SystemExit('worker first paint insertion marker missing')
s = s.replace(needle, replacement, 1)
p.write_text(s, encoding='utf-8')

# 4) Empty public endpoint is not authoritative: try the same Firebase SDK fallback used by the app.
p = root / 'frontend-react/src/lib/public-data.ts'
s = p.read_text(encoding='utf-8')
old = r'''      try {
        publicRows = await fetchDataset<Business>("/legacy-data/public-businesses-v1.json");
      } catch {
        const { loadAllBusinesses } = await import("./businesses");
        publicRows = await loadAllBusinesses(force);
      }

      let tourism: Business[] = [];'''
new = r'''      try {
        publicRows = await fetchDataset<Business>("/legacy-data/public-businesses-v1.json");
      } catch { /* Firebase fallback below */ }
      if (!publicRows.length) {
        try {
          const { loadAllBusinesses } = await import("./businesses");
          publicRows = await loadAllBusinesses(force);
        } catch { /* Static tourism still keeps discovery usable during quota limits. */ }
      }

      let tourism: Business[] = [];'''
if old not in s:
    raise SystemExit('public data business fallback marker missing')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')

# 5) Prevent Leaflet observer + timer double-start race.
p = root / 'frontend-react/src/pages/MapPage.tsx'
s = p.read_text(encoding='utf-8')
s = s.replace('    let disposed = false;\n    let fallback = 0;\n    let observer: IntersectionObserver | undefined;\n    const start = () => void (async () => {', '    let disposed = false;\n    let started = false;\n    let fallback = 0;\n    let observer: IntersectionObserver | undefined;\n    const start = () => {\n      if (disposed || started || mapRef.current) return;\n      started = true;\n      void (async () => {', 1)
s = s.replace('      } catch {\n        if (!disposed) { setMapReady(false); setMapError(true); }\n      }\n    })();', '      } catch (error) {\n        if (!disposed) { console.error("Leaflet init failed", error); setMapReady(false); setMapError(true); }\n      }\n      })();\n    };', 1)
s = s.replace('observer = new IntersectionObserver((entries) => { if (entries.some((entry) => entry.isIntersecting)) { observer?.disconnect(); start(); } }, { rootMargin: "500px 0px" });', 'observer = new IntersectionObserver((entries) => { if (entries.some((entry) => entry.isIntersecting)) { observer?.disconnect(); if (fallback) window.clearTimeout(fallback); fallback = 0; start(); } }, { rootMargin: "500px 0px" });', 1)
s = s.replace('      fallback = window.setTimeout(() => { observer?.disconnect(); start(); }, 1600);', '      fallback = window.setTimeout(() => { fallback = 0; observer?.disconnect(); start(); }, 1600);', 1)
p.write_text(s, encoding='utf-8')

# 6) Match the main Italian auth copy (without removing React functionality).
p = root / 'frontend-react/src/pages/AuthPage.tsx'
s = p.read_text(encoding='utf-8')
s = s.replace('registerHero: "Entra nella community.", heroText: "Usa il tuo account CalabriaVera per gestire profilo, preferiti, attività e messaggi."', 'registerHero: "Crea il tuo account", heroText: "Accedi per gestire attività, messaggi e preferiti."', 1)
p.write_text(s, encoding='utf-8')

print('Source-driven CSS, contacts, public data, map and auth parity patch applied')
