from pathlib import Path
p=Path('source/frontend-react/src/pages/MessagesPage.tsx')
s=p.read_text(encoding='utf-8')
old='function Avatar({ profile, name }: { profile?: PublicProfile | null; name: string }) { const src=String(profile?.avatarDataUrl||""); return <span className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-full bg-stone-200 text-sm font-black text-stone-600">{src ? <img src={src} alt="" className="h-full w-full object-cover" /> : String(name||"U").trim().charAt(0).toUpperCase()}</span>; }'
new='function Avatar({ profile, name, className="cv-conversation-avatar" }: { profile?: PublicProfile | null; name: string; className?: string }) { const src=String(profile?.avatarDataUrl||""); return <span className={`${className}${src?"":" cv-conversation-avatar--initial"}`}>{src ? <img src={src} alt="" /> : String(name||"U").trim().charAt(0).toUpperCase()}</span>; }'
if old not in s: raise SystemExit('Avatar marker missing')
s=s.replace(old,new,1)
s=s.replace('const field=document.getElementById("message-text") as HTMLTextAreaElement|null;', 'const field=document.getElementById("cv-message-input") as HTMLInputElement|HTMLTextAreaElement|null;',1)
start=s.index('  const selectedBusiness=')
end=s.rindex('\n}')
replacement=r'''  const selectedBusiness=selected?businesses[String(selected.businessId||"")]:undefined, selectedPeer=selected?peerId(selected,userId):"", selectedName=selected?nameFor(selected):c(copy,"select");
  return <section className="section container">
    <p className="eyebrow">CalabriaVera</p><h1>{c(copy,"title")}</h1>
    <div id="messages-root">
      {error?<div className="notice" role="alert"><strong>{error}</strong></div>:null}
      <div className="cv-messages-shell cv-messages-v2">
        <aside className="cv-conversations-panel">
          <div className="cv-messages-panel-head"><div><span className="eyebrow">{c(copy,"inbox")}</span><h2>{c(copy,"conversations")}</h2></div><span id="cv-conversation-total" className="cv-conversation-total">{visible.length}</span></div>
          <div className="cv-message-tools"><input id="cv-conversation-search" type="search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder={c(copy,"search")}/><div className="cv-message-filter">{(["all","unread","archived"] as Filter[]).map((value)=><button key={value} type="button" className={filter===value?"is-active":""} onClick={()=>setFilter(value)}>{c(copy,value)}</button>)}</div></div>
          <div id="conv-list" className="cv-conversation-list">{conversations===null?<div className="notice">Caricamento…</div>:visible.length?visible.map((row)=>{const peer=peerId(row,userId),business=businesses[String(row.businessId||"")],unread=unreadFor(row),archived=preferences[row.id]?.archived===true;return <div key={row.id} className={`cv-conversation-item ${selectedId===row.id?"is-active":""}`}>
            <button className={`cv-conversation-row ${unread?"has-unread":""}`} type="button" onClick={()=>choose(row)}><Avatar profile={profiles[peer]} name={nameFor(row)}/><span className="cv-conversation-copy"><span className="cv-conversation-top"><strong>{nameFor(row)}</strong><time>{formatTime(row.updatedAt,language)}</time></span><span className="cv-message-business">{localizedField<string>(business||{},"name",language)||business?.name||c(copy,"business")}</span><span className="cv-conversation-preview">{String(row.lastMessage||"")}</span></span>{unread?<span className="cv-unread-badge">{unread>99?"99+":unread}</span>:null}</button>
            <button type="button" className="cv-conversation-archive" onClick={()=>archive(row)}>{archived?c(copy,"restore"):c(copy,"archive")}</button><button type="button" className="cv-conversation-delete" aria-label={c(copy,"delete")} onClick={()=>void remove(row)}>×</button>
          </div>}):<div className="cv-messages-empty"><strong>{c(copy,"none")}</strong><p>{language==="it"?"Puoi contattare un’attività direttamente dalla sua scheda.":c(copy,"open")}</p><Link className="button button-primary" href={withLanguage("/catalogo",language)}>{language==="it"?"Esplora attività":c(copy,"business")}</Link></div>}</div>
        </aside>
        <section className="cv-thread-panel">
          <div id="thread-heading" className="cv-thread-heading">{selected?<><div className="cv-thread-contact"><Avatar profile={profiles[selectedPeer]} name={selectedName} className="cv-thread-avatar"/><div><span className="eyebrow">{c(copy,"conversation")}</span><h2>{selectedName}</h2><p>{localizedField<string>(selectedBusiness||{},"name",language)||selectedBusiness?.name||c(copy,"business")}</p></div></div><div className="cv-thread-actions"><button type="button" onClick={markUnread}>{c(copy,"markUnread")}</button><button type="button" onClick={()=>archive(selected)}>{preferences[selected.id]?.archived?c(copy,"restore"):c(copy,"archive")}</button><button type="button" className="cv-delete-chat" onClick={()=>void remove(selected)}>{c(copy,"delete")}</button>{selectedBusiness?<Link className="cv-thread-business-link" href={withLanguage(businessPath(selectedBusiness),language)}>{c(copy,"openBusiness")}</Link>:null}</div></>:<div><span className="eyebrow">{c(copy,"title")}</span><h2>{c(copy,"select")}</h2></div>}</div>
          <div id="thread" className="cv-thread">{messages===null?<div className="notice">Caricamento…</div>:messages.length?messages.map((message)=>{const mine=message.senderId===userId;return <div key={message.id} className={`cv-message-row ${mine?"is-mine":"is-theirs"}`}>{mine?null:<Avatar profile={profiles[selectedPeer]} name={selectedName} className="cv-message-sender-avatar"/>}<div className="cv-message-bubble"><p>{message.text}</p><div className="cv-message-meta"><time>{formatTime(message.createdAt,language)}</time>{mine?<span className={`cv-message-state ${message.readAt?"is-read":""}`} aria-label={message.readAt?"Letto":"Inviato"}>{message.readAt?"✓✓":"✓"}</span>:null}</div></div></div>}):<div className="cv-thread-placeholder"><p>{selected?c(copy,"first"):c(copy,"open")}</p></div>}</div>
          <div className="cv-quick-replies">{editingReplies?<div className="cv-quick-replies-editor"><label>{c(copy,"quickReplies")}<textarea value={replyDraft} onChange={(e)=>setReplyDraft(e.target.value)} rows={4}/></label><p className="muted small">{c(copy,"editHint")}</p><div className="form-actions"><button type="button" className="button button-primary" onClick={saveReplies}>{c(copy,"saveReplies")}</button><button type="button" className="button button-secondary" onClick={()=>setEditingReplies(false)}>{c(copy,"cancel")}</button></div></div>:<><div className="cv-quick-replies-head"><strong>{c(copy,"quickReplies")}</strong><button type="button" onClick={()=>setEditingReplies(true)}>{c(copy,"editReplies")}</button></div><div id="cv-quick-reply-list">{quickReplies.map((reply,index)=><button key={`${index}-${reply}`} type="button" disabled={!selected} onClick={()=>applyQuick(reply)}>{reply}</button>)}</div></>}</div>
          <form id="send-form" className="cv-message-composer" onSubmit={submit}><label className="sr-only" htmlFor="cv-message-input">{c(copy,"message")}</label><input id="cv-message-input" name="message" required maxLength={2000} placeholder={c(copy,"placeholder")} disabled={!selected}/><button className="cv-send-button" type="submit" disabled={!selected||busy}><span>{c(copy,"send")}</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 3 18 9-18 9 4-9-4-9Zm4 9h14"/></svg></button></form>
        </section>
      </div>
    </div>
  </section>;'''
s=s[:start]+replacement+s[end:]
for marker in ['id="messages-root"','cv-messages-shell cv-messages-v2','cv-conversation-row','cv-thread-heading','cv-thread-actions','cv-delete-chat','cv-message-composer','cv-send-button']:
    if marker not in s: raise SystemExit(f'missing {marker}')
p.write_text(s,encoding='utf-8')
print('MESSAGES_DOM_PARITY_PATCHED')
