from pathlib import Path

p = Path('source/frontend-react/src/pages/BusinessEditorPage.tsx')
s = p.read_text(encoding='utf-8')

replacements = [
  (
    '<section className="mx-auto max-w-6xl px-5 py-12 lg:px-8 lg:py-16">\n      <div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Per le imprese locali</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">{editId ? "Modifica attività" : "Aggiungi la tua attività"}</h1><p className="mt-3 max-w-2xl text-stone-600">Stesso account, stessi dati Firebase. Puoi correggere con precisione posizione e galleria prima di salvare.</p></div><Link href="/dashboard" className="rounded-full border border-stone-300 bg-white px-4 py-2 text-sm font-black">Dashboard</Link></div>',
    '<section className="section container mx-auto max-w-6xl px-5 py-12 lg:px-8 lg:py-16">\n      <div className="section-heading form-intro mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-xs font-black uppercase tracking-[.16em] text-emerald-700">Per le imprese locali</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">{editId ? "Modifica attività" : "Aggiungi la tua attività"}</h1><p className="prose muted mt-3 max-w-2xl text-stone-600">{editId ? "Aggiorna informazioni, servizi e immagini." : "Scegli prima la categoria generale e poi il tipo preciso di attività."}</p></div><div className="form-progress"><span>1 · Identità</span><span>2 · Posizione</span><span>3 · Servizi</span><span>4 · Info utili</span><span>5 · Contatti e foto</span></div></div>'
  ),
  ('<form id="react-business-form" onSubmit={submit} className="grid gap-6">', '<form id="react-business-form" onSubmit={submit} className="business-form grid gap-6" noValidate={false}>'),
  ('<section className="rounded-[1.7rem] border border-stone-200 bg-white p-6 shadow-sm sm:p-8">\n          <div className="mb-6"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">1 · Identità</p><h2 className="mt-2 text-2xl font-black">Informazioni principali</h2></div>', '<section className="card form-section rounded-[1.7rem] border border-stone-200 bg-white p-6 shadow-sm sm:p-8">\n          <div className="form-section-title mb-6"><span>1</span><div><h2 className="mt-2 text-2xl font-black">Informazioni principali</h2><p>La categoria serve a raggruppare; il tipo identifica esattamente l’attività.</p></div></div>'),
  ('<label className="text-sm font-bold">Civico<input name="streetNumber" defaultValue={field(existing?.streetNumber) || parsedAddress.streetNumber} maxLength={30} className={input} /></label>', '<label className="text-sm font-bold">Numero civico <b>*</b><input name="streetNumber" defaultValue={field(existing?.streetNumber) || parsedAddress.streetNumber} required maxLength={20} className={input} /></label>'),
  ('<label className="text-sm font-bold">CAP<input name="cap" defaultValue={field(existing?.cap)} inputMode="numeric" maxLength={10} className={input} /></label>', '<label className="text-sm font-bold">CAP <b>*</b><input name="cap" defaultValue={field(existing?.cap)} required inputMode="numeric" pattern="[0-9]{5}" maxLength={5} className={input} /></label>'),
  ('<label className="text-sm font-bold">Telefono<input name="phone" type="tel" defaultValue={field(existing?.phone)} maxLength={40} className={input} /></label>', '<label className="text-sm font-bold">Telefono <b>*</b><input name="phone" type="tel" defaultValue={field(existing?.phone)} required maxLength={40} autoComplete="tel" className={input} /></label>'),
  ('<div className="sticky bottom-3 z-20 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-stone-200 bg-white/95 p-4 shadow-xl backdrop-blur"><p className="text-sm text-stone-500">{editId ? "Le modifiche mantengono proprietario, stato e verifica esistenti." : "La nuova scheda sarà inviata in moderazione."}</p><button type="submit" disabled={busy || imageBusy || !emailVerified} className="rounded-xl bg-emerald-700 px-7 py-3 font-black text-white disabled:cursor-not-allowed disabled:opacity-50">{busy ? "Salvataggio…" : editId ? "Salva modifiche" : "Invia attività"}</button></div>', '<section className="card form-section form-confirm"><div className="cv-consent-row cv-business-consent"><input id="business-truthful" type="checkbox" name="truthful" required defaultChecked={Boolean(editId)} /><label htmlFor="business-truthful">Dichiaro che i dati sono corretti e che sono autorizzato a rappresentare questa attività. <b>*</b></label></div></section><div className="form-actions sticky-form-actions sticky bottom-3 z-20 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-stone-200 bg-white/95 p-4 shadow-xl backdrop-blur"><p className="text-sm text-stone-500">{editId ? "Le modifiche mantengono proprietario, stato e verifica esistenti." : "La nuova scheda sarà inviata in moderazione."}</p><button id="business-submit" type="submit" disabled={busy || imageBusy || !emailVerified} className="button button-primary rounded-xl bg-emerald-700 px-7 py-3 font-black text-white disabled:cursor-not-allowed disabled:opacity-50">{busy ? "Salvataggio…" : editId ? "Salva modifiche" : "Invia per approvazione"}</button>{editId ? <Link className="button button-secondary" href="/dashboard">Annulla</Link> : null}</div>')
]

for old, new in replacements:
    if old not in s:
        raise SystemExit(f'marker missing: {old[:100]}')
    s = s.replace(old, new, 1)

# Bring remaining sections under the same legacy card hook without changing React layout behavior.
s = s.replace('className="rounded-[1.7rem] border border-stone-200 bg-white p-6 shadow-sm sm:p-8"', 'className="card form-section rounded-[1.7rem] border border-stone-200 bg-white p-6 shadow-sm sm:p-8"')

p.write_text(s, encoding='utf-8')
print('Business editor contract parity patch applied')
